name: bilhikma
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ^3.12.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  easy_localization: ^3.0.8
  dio: ^5.11.0
  flutter_bloc: ^9.1.1
  screen_protector: ^1.5.3
  flutter_svg: ^2.2.1
  google_fonts: ^8.2.1
  uuid: ^4.6.0
  device_info_plus: ^13.2.0
  package_info_plus: ^10.2.1
  flutter_secure_storage: ^10.3.1
  curved_labeled_navigation_bar: ^2.0.6
  get_it: ^9.2.1
  flutter_screenutil: ^5.9.3
  audio_service: ^0.18.19
  just_audio: ^0.10.6
  youtube_player_flutter: ^9.1.1
  video_player: ^2.13.0
  floating: ^6.0.0
  just_audio_background: ^0.0.1-beta.17
  share_plus: ^13.3.0
  path: ^1.9.0
  path_provider: ^2.1.5
  flutter_animate: ^4.5.2
  syncfusion_flutter_pdf: ^34.2.3
  pinput: ^6.0.2
  firebase_core: ^4.13.0
  firebase_messaging: ^16.5.0
  flutter_local_notifications: ^22.3.0
  syncfusion_flutter_pdfviewer: ^34.2.3
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
flutter_native_splash:
  color: "#EEE2CB"
  color_dark: "#171717"
  image: assets/app_icon_splash.png
  image_dark: assets/app_icon_splash.png
  android: true
  ios: false
  web: false
  android_12:
    image: assets/app_icon_splash.png
    color: "#EEE2CB"
    image_dark: assets/app_icon_splash.png
    color_dark: "#171717"
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants/
  filename: assets.dart