import '../models/country_model.dart';

/// Dialling countries, their calling codes and national-number digit bounds.
///
/// Names live here rather than in the translation files because the list is
/// large, static and only ever rendered in the country picker.
class AppCountries {
  AppCountries._();

  /// Pre-selected country — the app's primary market.
  static const String defaultIsoCode = 'SY';

  static Country get defaultCountry => byIso(defaultIsoCode) ?? all.first;

  static Country? byIso(String isoCode) {
    final String code = isoCode.toUpperCase();
    for (final Country country in all) {
      if (country.isoCode == code) return country;
    }

    return null;
  }

  /// Resolves a stored full number (`+963958953288`) back to its country and
  /// national part, so a remembered identity repopulates both fields.
  ///
  /// Returns `null` when [fullNumber] carries no recognisable calling code —
  /// a bare local number, for instance.
  static ({Country country, String nationalNumber})? parse(String fullNumber) {
    final String digits = fullNumber.replaceAll(RegExp(r'[^\d+]'), '');
    if (!digits.startsWith('+') && !digits.startsWith('00')) return null;

    final String withoutPrefix = digits.startsWith('+')
        ? digits.substring(1)
        : digits.substring(2);

    Country? best;
    for (final Country country in all) {
      if (!withoutPrefix.startsWith(country.dialCode)) continue;
      // Longest calling code wins, so +1268 beats +1.
      if (best == null || country.dialCode.length > best.dialCode.length) {
        best = country;
      }
    }

    if (best == null) return null;

    return (
      country: best,
      nationalNumber: withoutPrefix.substring(best.dialCode.length),
    );
  }

  /// Ordered so the app's main markets surface first, then everything else
  /// alphabetically by English name.
  static const List<Country> all = <Country>[
    Country('SY', '963', 'Syria', 'سوريا', minLength: 9, maxLength: 9),
    Country(
      'SA',
      '966',
      'Saudi Arabia',
      'السعودية',
      minLength: 9,
      maxLength: 9,
    ),
    Country(
      'AE',
      '971',
      'United Arab Emirates',
      'الإمارات العربية المتحدة',
      minLength: 9,
      maxLength: 9,
    ),
    Country('EG', '20', 'Egypt', 'مصر', minLength: 10, maxLength: 10),
    Country('TR', '90', 'Turkey', 'تركيا', minLength: 10, maxLength: 10),
    Country('JO', '962', 'Jordan', 'الأردن', minLength: 9, maxLength: 9),
    Country('LB', '961', 'Lebanon', 'لبنان', minLength: 7, maxLength: 8),
    Country('IQ', '964', 'Iraq', 'العراق', minLength: 10, maxLength: 10),
    Country('KW', '965', 'Kuwait', 'الكويت', minLength: 8, maxLength: 8),
    Country('QA', '974', 'Qatar', 'قطر', minLength: 8, maxLength: 8),

    Country('AF', '93', 'Afghanistan', 'أفغانستان', minLength: 9, maxLength: 9),
    Country('AL', '355', 'Albania', 'ألبانيا', minLength: 9, maxLength: 9),
    Country('DZ', '213', 'Algeria', 'الجزائر', minLength: 9, maxLength: 9),
    Country('AD', '376', 'Andorra', 'أندورا', minLength: 6, maxLength: 9),
    Country('AO', '244', 'Angola', 'أنغولا', minLength: 9, maxLength: 9),
    Country(
      'AG',
      '1268',
      'Antigua and Barbuda',
      'أنتيغوا وبربودا',
      minLength: 7,
      maxLength: 7,
    ),
    Country(
      'AR',
      '54',
      'Argentina',
      'الأرجنتين',
      minLength: 10,
      maxLength: 11,
    ),
    Country('AM', '374', 'Armenia', 'أرمينيا', minLength: 8, maxLength: 8),
    Country('AU', '61', 'Australia', 'أستراليا', minLength: 9, maxLength: 9),
    Country('AT', '43', 'Austria', 'النمسا', minLength: 10, maxLength: 13),
    Country(
      'AZ',
      '994',
      'Azerbaijan',
      'أذربيجان',
      minLength: 9,
      maxLength: 9,
    ),
    Country('BS', '1242', 'Bahamas', 'الباهاما', minLength: 7, maxLength: 7),
    Country('BH', '973', 'Bahrain', 'البحرين', minLength: 8, maxLength: 8),
    Country(
      'BD',
      '880',
      'Bangladesh',
      'بنغلاديش',
      minLength: 10,
      maxLength: 10,
    ),
    Country('BB', '1246', 'Barbados', 'بربادوس', minLength: 7, maxLength: 7),
    Country('BY', '375', 'Belarus', 'بيلاروسيا', minLength: 9, maxLength: 9),
    Country('BE', '32', 'Belgium', 'بلجيكا', minLength: 9, maxLength: 9),
    Country('BZ', '501', 'Belize', 'بليز', minLength: 7, maxLength: 7),
    Country('BJ', '229', 'Benin', 'بنين', minLength: 8, maxLength: 8),
    Country('BT', '975', 'Bhutan', 'بوتان', minLength: 8, maxLength: 8),
    Country('BO', '591', 'Bolivia', 'بوليفيا', minLength: 8, maxLength: 8),
    Country(
      'BA',
      '387',
      'Bosnia and Herzegovina',
      'البوسنة والهرسك',
      minLength: 8,
      maxLength: 8,
    ),
    Country('BW', '267', 'Botswana', 'بوتسوانا', minLength: 7, maxLength: 8),
    Country('BR', '55', 'Brazil', 'البرازيل', minLength: 10, maxLength: 11),
    Country('BN', '673', 'Brunei', 'بروناي', minLength: 7, maxLength: 7),
    Country('BG', '359', 'Bulgaria', 'بلغاريا', minLength: 8, maxLength: 9),
    Country(
      'BF',
      '226',
      'Burkina Faso',
      'بوركينا فاسو',
      minLength: 8,
      maxLength: 8,
    ),
    Country('BI', '257', 'Burundi', 'بوروندي', minLength: 8, maxLength: 8),
    Country('KH', '855', 'Cambodia', 'كمبوديا', minLength: 8, maxLength: 9),
    Country('CM', '237', 'Cameroon', 'الكاميرون', minLength: 9, maxLength: 9),
    Country('CA', '1', 'Canada', 'كندا', minLength: 10, maxLength: 10),
    Country('CV', '238', 'Cape Verde', 'الرأس الأخضر', minLength: 7, maxLength: 7),
    Country(
      'CF',
      '236',
      'Central African Republic',
      'جمهورية أفريقيا الوسطى',
      minLength: 8,
      maxLength: 8,
    ),
    Country('TD', '235', 'Chad', 'تشاد', minLength: 8, maxLength: 8),
    Country('CL', '56', 'Chile', 'تشيلي', minLength: 9, maxLength: 9),
    Country('CN', '86', 'China', 'الصين', minLength: 11, maxLength: 11),
    Country('CO', '57', 'Colombia', 'كولومبيا', minLength: 10, maxLength: 10),
    Country('KM', '269', 'Comoros', 'جزر القمر', minLength: 7, maxLength: 7),
    Country(
      'CD',
      '243',
      'Congo (DRC)',
      'الكونغو الديمقراطية',
      minLength: 9,
      maxLength: 9,
    ),
    Country(
      'CG',
      '242',
      'Congo (Republic)',
      'الكونغو',
      minLength: 9,
      maxLength: 9,
    ),
    Country('CR', '506', 'Costa Rica', 'كوستاريكا', minLength: 8, maxLength: 8),
    Country(
      'CI',
      '225',
      "Côte d'Ivoire",
      'ساحل العاج',
      minLength: 10,
      maxLength: 10,
    ),
    Country('HR', '385', 'Croatia', 'كرواتيا', minLength: 8, maxLength: 9),
    Country('CU', '53', 'Cuba', 'كوبا', minLength: 8, maxLength: 8),
    Country('CY', '357', 'Cyprus', 'قبرص', minLength: 8, maxLength: 8),
    Country('CZ', '420', 'Czechia', 'التشيك', minLength: 9, maxLength: 9),
    Country('DK', '45', 'Denmark', 'الدنمارك', minLength: 8, maxLength: 8),
    Country('DJ', '253', 'Djibouti', 'جيبوتي', minLength: 8, maxLength: 8),
    Country('DM', '1767', 'Dominica', 'دومينيكا', minLength: 7, maxLength: 7),
    Country(
      'DO',
      '1809',
      'Dominican Republic',
      'جمهورية الدومينيكان',
      minLength: 7,
      maxLength: 7,
    ),
    Country('EC', '593', 'Ecuador', 'الإكوادور', minLength: 9, maxLength: 9),
    Country('SV', '503', 'El Salvador', 'السلفادور', minLength: 8, maxLength: 8),
    Country(
      'GQ',
      '240',
      'Equatorial Guinea',
      'غينيا الاستوائية',
      minLength: 9,
      maxLength: 9,
    ),
    Country('ER', '291', 'Eritrea', 'إريتريا', minLength: 7, maxLength: 7),
    Country('EE', '372', 'Estonia', 'إستونيا', minLength: 7, maxLength: 8),
    Country('SZ', '268', 'Eswatini', 'إسواتيني', minLength: 8, maxLength: 8),
    Country('ET', '251', 'Ethiopia', 'إثيوبيا', minLength: 9, maxLength: 9),
    Country('FJ', '679', 'Fiji', 'فيجي', minLength: 7, maxLength: 7),
    Country('FI', '358', 'Finland', 'فنلندا', minLength: 9, maxLength: 10),
    Country('FR', '33', 'France', 'فرنسا', minLength: 9, maxLength: 9),
    Country('GA', '241', 'Gabon', 'الغابون', minLength: 8, maxLength: 8),
    Country('GM', '220', 'Gambia', 'غامبيا', minLength: 7, maxLength: 7),
    Country('GE', '995', 'Georgia', 'جورجيا', minLength: 9, maxLength: 9),
    Country('DE', '49', 'Germany', 'ألمانيا', minLength: 10, maxLength: 11),
    Country('GH', '233', 'Ghana', 'غانا', minLength: 9, maxLength: 9),
    Country('GR', '30', 'Greece', 'اليونان', minLength: 10, maxLength: 10),
    Country('GD', '1473', 'Grenada', 'غرينادا', minLength: 7, maxLength: 7),
    Country('GT', '502', 'Guatemala', 'غواتيمالا', minLength: 8, maxLength: 8),
    Country('GN', '224', 'Guinea', 'غينيا', minLength: 9, maxLength: 9),
    Country(
      'GW',
      '245',
      'Guinea-Bissau',
      'غينيا بيساو',
      minLength: 7,
      maxLength: 7,
    ),
    Country('GY', '592', 'Guyana', 'غيانا', minLength: 7, maxLength: 7),
    Country('HT', '509', 'Haiti', 'هايتي', minLength: 8, maxLength: 8),
    Country('HN', '504', 'Honduras', 'هندوراس', minLength: 8, maxLength: 8),
    Country('HK', '852', 'Hong Kong', 'هونغ كونغ', minLength: 8, maxLength: 8),
    Country('HU', '36', 'Hungary', 'المجر', minLength: 9, maxLength: 9),
    Country('IS', '354', 'Iceland', 'آيسلندا', minLength: 7, maxLength: 7),
    Country('IN', '91', 'India', 'الهند', minLength: 10, maxLength: 10),
    Country('ID', '62', 'Indonesia', 'إندونيسيا', minLength: 9, maxLength: 12),
    Country('IR', '98', 'Iran', 'إيران', minLength: 10, maxLength: 10),
    Country('IE', '353', 'Ireland', 'أيرلندا', minLength: 9, maxLength: 9),
    Country('IT', '39', 'Italy', 'إيطاليا', minLength: 9, maxLength: 11),
    Country('JM', '1876', 'Jamaica', 'جامايكا', minLength: 7, maxLength: 7),
    Country('JP', '81', 'Japan', 'اليابان', minLength: 10, maxLength: 10),
    Country(
      'KZ',
      '7',
      'Kazakhstan',
      'كازاخستان',
      minLength: 10,
      maxLength: 10,
    ),
    Country('KE', '254', 'Kenya', 'كينيا', minLength: 9, maxLength: 9),
    Country('KI', '686', 'Kiribati', 'كيريباتي', minLength: 5, maxLength: 8),
    Country('XK', '383', 'Kosovo', 'كوسوفو', minLength: 8, maxLength: 9),
    Country(
      'KG',
      '996',
      'Kyrgyzstan',
      'قيرغيزستان',
      minLength: 9,
      maxLength: 9,
    ),
    Country('LA', '856', 'Laos', 'لاوس', minLength: 9, maxLength: 10),
    Country('LV', '371', 'Latvia', 'لاتفيا', minLength: 8, maxLength: 8),
    Country('LS', '266', 'Lesotho', 'ليسوتو', minLength: 8, maxLength: 8),
    Country('LR', '231', 'Liberia', 'ليبيريا', minLength: 8, maxLength: 9),
    Country('LY', '218', 'Libya', 'ليبيا', minLength: 9, maxLength: 9),
    Country(
      'LI',
      '423',
      'Liechtenstein',
      'ليختنشتاين',
      minLength: 7,
      maxLength: 7,
    ),
    Country('LT', '370', 'Lithuania', 'ليتوانيا', minLength: 8, maxLength: 8),
    Country('LU', '352', 'Luxembourg', 'لوكسمبورغ', minLength: 9, maxLength: 9),
    Country('MO', '853', 'Macau', 'ماكاو', minLength: 8, maxLength: 8),
    Country('MG', '261', 'Madagascar', 'مدغشقر', minLength: 9, maxLength: 9),
    Country('MW', '265', 'Malawi', 'مالاوي', minLength: 9, maxLength: 9),
    Country('MY', '60', 'Malaysia', 'ماليزيا', minLength: 9, maxLength: 10),
    Country('MV', '960', 'Maldives', 'المالديف', minLength: 7, maxLength: 7),
    Country('ML', '223', 'Mali', 'مالي', minLength: 8, maxLength: 8),
    Country('MT', '356', 'Malta', 'مالطا', minLength: 8, maxLength: 8),
    Country('MR', '222', 'Mauritania', 'موريتانيا', minLength: 8, maxLength: 8),
    Country('MU', '230', 'Mauritius', 'موريشيوس', minLength: 7, maxLength: 8),
    Country('MX', '52', 'Mexico', 'المكسيك', minLength: 10, maxLength: 10),
    Country('MD', '373', 'Moldova', 'مولدوفا', minLength: 8, maxLength: 8),
    Country('MC', '377', 'Monaco', 'موناكو', minLength: 8, maxLength: 9),
    Country('MN', '976', 'Mongolia', 'منغوليا', minLength: 8, maxLength: 8),
    Country('ME', '382', 'Montenegro', 'الجبل الأسود', minLength: 8, maxLength: 8),
    Country('MA', '212', 'Morocco', 'المغرب', minLength: 9, maxLength: 9),
    Country('MZ', '258', 'Mozambique', 'موزمبيق', minLength: 9, maxLength: 9),
    Country('MM', '95', 'Myanmar', 'ميانمار', minLength: 8, maxLength: 10),
    Country('NA', '264', 'Namibia', 'ناميبيا', minLength: 9, maxLength: 9),
    Country('NP', '977', 'Nepal', 'نيبال', minLength: 10, maxLength: 10),
    Country('NL', '31', 'Netherlands', 'هولندا', minLength: 9, maxLength: 9),
    Country('NZ', '64', 'New Zealand', 'نيوزيلندا', minLength: 8, maxLength: 10),
    Country('NI', '505', 'Nicaragua', 'نيكاراغوا', minLength: 8, maxLength: 8),
    Country('NE', '227', 'Niger', 'النيجر', minLength: 8, maxLength: 8),
    Country('NG', '234', 'Nigeria', 'نيجيريا', minLength: 10, maxLength: 10),
    Country('KP', '850', 'North Korea', 'كوريا الشمالية', minLength: 4, maxLength: 10),
    Country(
      'MK',
      '389',
      'North Macedonia',
      'مقدونيا الشمالية',
      minLength: 8,
      maxLength: 8,
    ),
    Country('NO', '47', 'Norway', 'النرويج', minLength: 8, maxLength: 8),
    Country('OM', '968', 'Oman', 'عُمان', minLength: 8, maxLength: 8),
    Country('PK', '92', 'Pakistan', 'باكستان', minLength: 10, maxLength: 10),
    Country('PS', '970', 'Palestine', 'فلسطين', minLength: 9, maxLength: 9),
    Country('PA', '507', 'Panama', 'بنما', minLength: 8, maxLength: 8),
    Country(
      'PG',
      '675',
      'Papua New Guinea',
      'بابوا غينيا الجديدة',
      minLength: 8,
      maxLength: 8,
    ),
    Country('PY', '595', 'Paraguay', 'باراغواي', minLength: 9, maxLength: 9),
    Country('PE', '51', 'Peru', 'بيرو', minLength: 9, maxLength: 9),
    Country(
      'PH',
      '63',
      'Philippines',
      'الفلبين',
      minLength: 10,
      maxLength: 10,
    ),
    Country('PL', '48', 'Poland', 'بولندا', minLength: 9, maxLength: 9),
    Country('PT', '351', 'Portugal', 'البرتغال', minLength: 9, maxLength: 9),
    Country('PR', '1787', 'Puerto Rico', 'بورتوريكو', minLength: 7, maxLength: 7),
    Country('RO', '40', 'Romania', 'رومانيا', minLength: 9, maxLength: 9),
    Country('RU', '7', 'Russia', 'روسيا', minLength: 10, maxLength: 10),
    Country('RW', '250', 'Rwanda', 'رواندا', minLength: 9, maxLength: 9),
    Country(
      'KN',
      '1869',
      'Saint Kitts and Nevis',
      'سانت كيتس ونيفيس',
      minLength: 7,
      maxLength: 7,
    ),
    Country(
      'LC',
      '1758',
      'Saint Lucia',
      'سانت لوسيا',
      minLength: 7,
      maxLength: 7,
    ),
    Country(
      'VC',
      '1784',
      'Saint Vincent and the Grenadines',
      'سانت فنسنت والغرينادين',
      minLength: 7,
      maxLength: 7,
    ),
    Country('WS', '685', 'Samoa', 'ساموا', minLength: 5, maxLength: 7),
    Country('SM', '378', 'San Marino', 'سان مارينو', minLength: 8, maxLength: 10),
    Country('SN', '221', 'Senegal', 'السنغال', minLength: 9, maxLength: 9),
    Country('RS', '381', 'Serbia', 'صربيا', minLength: 8, maxLength: 9),
    Country('SC', '248', 'Seychelles', 'سيشل', minLength: 7, maxLength: 7),
    Country(
      'SL',
      '232',
      'Sierra Leone',
      'سيراليون',
      minLength: 8,
      maxLength: 8,
    ),
    Country('SG', '65', 'Singapore', 'سنغافورة', minLength: 8, maxLength: 8),
    Country('SK', '421', 'Slovakia', 'سلوفاكيا', minLength: 9, maxLength: 9),
    Country('SI', '386', 'Slovenia', 'سلوفينيا', minLength: 8, maxLength: 8),
    Country(
      'SB',
      '677',
      'Solomon Islands',
      'جزر سليمان',
      minLength: 5,
      maxLength: 7,
    ),
    Country('SO', '252', 'Somalia', 'الصومال', minLength: 7, maxLength: 9),
    Country(
      'ZA',
      '27',
      'South Africa',
      'جنوب أفريقيا',
      minLength: 9,
      maxLength: 9,
    ),
    Country(
      'KR',
      '82',
      'South Korea',
      'كوريا الجنوبية',
      minLength: 9,
      maxLength: 10,
    ),
    Country(
      'SS',
      '211',
      'South Sudan',
      'جنوب السودان',
      minLength: 9,
      maxLength: 9,
    ),
    Country('ES', '34', 'Spain', 'إسبانيا', minLength: 9, maxLength: 9),
    Country('LK', '94', 'Sri Lanka', 'سريلانكا', minLength: 9, maxLength: 9),
    Country('SD', '249', 'Sudan', 'السودان', minLength: 9, maxLength: 9),
    Country('SR', '597', 'Suriname', 'سورينام', minLength: 6, maxLength: 7),
    Country('SE', '46', 'Sweden', 'السويد', minLength: 7, maxLength: 9),
    Country('CH', '41', 'Switzerland', 'سويسرا', minLength: 9, maxLength: 9),
    Country('TW', '886', 'Taiwan', 'تايوان', minLength: 9, maxLength: 9),
    Country(
      'TJ',
      '992',
      'Tajikistan',
      'طاجيكستان',
      minLength: 9,
      maxLength: 9,
    ),
    Country('TZ', '255', 'Tanzania', 'تنزانيا', minLength: 9, maxLength: 9),
    Country('TH', '66', 'Thailand', 'تايلاند', minLength: 9, maxLength: 9),
    Country(
      'TL',
      '670',
      'Timor-Leste',
      'تيمور الشرقية',
      minLength: 7,
      maxLength: 8,
    ),
    Country('TG', '228', 'Togo', 'توغو', minLength: 8, maxLength: 8),
    Country('TO', '676', 'Tonga', 'تونغا', minLength: 5, maxLength: 7),
    Country(
      'TT',
      '1868',
      'Trinidad and Tobago',
      'ترينيداد وتوباغو',
      minLength: 7,
      maxLength: 7,
    ),
    Country('TN', '216', 'Tunisia', 'تونس', minLength: 8, maxLength: 8),
    Country(
      'TM',
      '993',
      'Turkmenistan',
      'تركمانستان',
      minLength: 8,
      maxLength: 8,
    ),
    Country('UG', '256', 'Uganda', 'أوغندا', minLength: 9, maxLength: 9),
    Country('UA', '380', 'Ukraine', 'أوكرانيا', minLength: 9, maxLength: 9),
    Country(
      'GB',
      '44',
      'United Kingdom',
      'المملكة المتحدة',
      minLength: 10,
      maxLength: 10,
    ),
    Country(
      'US',
      '1',
      'United States',
      'الولايات المتحدة',
      minLength: 10,
      maxLength: 10,
    ),
    Country('UY', '598', 'Uruguay', 'أوروغواي', minLength: 8, maxLength: 8),
    Country(
      'UZ',
      '998',
      'Uzbekistan',
      'أوزبكستان',
      minLength: 9,
      maxLength: 9,
    ),
    Country('VU', '678', 'Vanuatu', 'فانواتو', minLength: 5, maxLength: 7),
    Country(
      'VA',
      '379',
      'Vatican City',
      'الفاتيكان',
      minLength: 8,
      maxLength: 10,
    ),
    Country(
      'VE',
      '58',
      'Venezuela',
      'فنزويلا',
      minLength: 10,
      maxLength: 10,
    ),
    Country('VN', '84', 'Vietnam', 'فيتنام', minLength: 9, maxLength: 10),
    Country('YE', '967', 'Yemen', 'اليمن', minLength: 9, maxLength: 9),
    Country('ZM', '260', 'Zambia', 'زامبيا', minLength: 9, maxLength: 9),
    Country('ZW', '263', 'Zimbabwe', 'زيمبابوي', minLength: 9, maxLength: 9),
  ];
}
